#!/bin/bash

echo "==== GitHub Repository Setup Guide ===="
echo "Follow these steps to push this frontend to a new GitHub repository."
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Name your repository (e.g., officestonks-frontend)"
echo "   - Do NOT initialize with README, .gitignore, or license"
echo "   - Click 'Create repository'"
echo ""
echo "2. Run the commands below (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/officestonks-frontend.git"
echo "   git push -u origin main"
echo ""
echo "3. Your repository is now on GitHub!"
echo ""
echo "Notes:"
echo "- Railway is already configured via railway.json"
echo "- The frontend is already built and ready to deploy"
echo "- The API URL is configured in .env"
echo ""
echo "See GITHUB_SETUP.md for more detailed instructions."